#!/bin/bash
#################################################################################
# The coordinates are mapped to standard bluestacks screen dimension. You can use
# this script with any deviced connected over usb but you will need to update
# the x/y coords of everything.
#
# To use: Craft your own main loop below to suit your needs
# chmod 755 heal
# ./heal 3 false
if [ "$#" -ne 2 ]
then
  echo "Usage: heal <tank player slot (1-7)> true|false (enable hotkey gear)"
  exit 1
fi
function target {
  case "$1" in
        1)
          echo adb shell input tap 335 200 # x & y of player slot 1
          ;;
        2)
          echo adb shell input tap 335 275 # x & y of player slot 2
          ;;
        3)
          echo adb shell input tap 335 345 # x & y of player slot 3
          ;;
        4)
          echo adb shell input tap 335 415 # x & y of player slot 4
          ;;
        5)
          echo adb shell input tap 335 490 # x & y of player slot 5
          ;;
        6)
          echo adb shell input tap 335 565 # x & y of player slot 6
          ;;
        7)
          echo adb shell input tap 335 640 # x & y of player slot 7
          ;;
  esac
}

function cast {
  case "$1" in
    1)
      echo adb shell input tap 1581 97 # x & y of spell slot 1
      ;;
    2)
      echo adb shell input tap 1720 97 # x & y of spell slot 2
      ;;
    3)
      echo adb shell input tap 1581 197 # x & y of spell slot 3
      ;;
    4)
      echo adb shell input tap 1720 97 # x & y of spell slot 4
      ;;
    5)
      echo adb shell input tap 1581 97 # x & y of spell slot 5
      ;;
    6)
      echo adb shell input tap 1720 97 # x & y of spell slot 6
      ;;
    7)
      echo adb shell input tap 1581 97 # x & y of spell slot 7
      ;;
    8)
      echo adb shell input tap 1720 97 # x & y of spell slot 8
      ;;
  esac
  sleep 0.25
}

function maybeResurect {
  sleep 0.5
  echo ensuring not dead
  echo adb shell input tap 894 510
  sleep 0.5
}

function targetTank {
  echo targeting tank
  sleep 0.5
  target $1
  sleep 0.5
}

################################################################################
# The following is your "loop"
# Each loop should be customized to a specific char. In my case, I equip two items
# for touch, and two items for breath before each cast. Because I use hotkeys sometimes
# when I use occult, but NOT when I use EDL I added a flag to enable/disable the Usage
# of hotkeyed items.

function touch { # helper function for casting touch
  if [ $1 = "true" ]; then
    cast 6
    cast 4
  fi
  targetTank
  cast 2
  maybeResurect
  sleep 1
}

function breath { # helper function for casting breath
  if [ $1 = "true" ]; then
    cast 5
    cast 3
  fi
  targetTank
  cast 2
  maybeResurect
  sleep 1
}
while :
  do
    clear
    maybeResurect
    touch $2
    breath $2
    touch $2
    breath $2
    touch $2
    breath $2
    # others 
    cast 7
    sleep 1
    cast 8
    sleep 1
  done
